// Please do NOT edit this file directlly
// To synchronize set/update project configs:
// + From terminal, run $ sheetbase config set key=value|...
// + Or, edit configs in sheetbase.json, then run $ sheetbase config update
export const SHEETBASE_CONFIG = {
  "backendUrl": "https://script.google.com/macros/s/AKfycbwxZN0TFrVSrE7RPdcUJgfswfxbA3VIYhXnPIHAQ4ut1BQdVeFnNkL_0yNmgyYuKY76BQ/exec"
};
